SIMPLE_SNIPPETS = [
    "Omar Khaled is Artificial Intelligence Engineer with 3+ years of experience at the intersection of research and development. Skilled in LLM fine-tuning, reinforcement learning, RAG systems, voice AI agents, and AI automation. Hands-on contributions include improving reasoning accuracy, optimizing efficiency, and deploying enterprise-ready solutions such as real-time conversational agents, automation platforms, and scalable retrieval systems.",
    "Mohamed Samy is a Frontend Developer with 3 years of experience specializing in React and Next.js. Skilled in building scalable, high-performance web applications with responsive UI/UX. Strong background in integrating APIs and optimizing frontend performance for modern web platforms.",
    "Hossam Hassan has 5 years of experience as a Backend Engineer, specializing in Node.js, Express, and PostgreSQL. Proven expertise in designing RESTful APIs, microservices, and high-load systems. Adept at improving scalability, database optimization, and backend security practices.",
    "Sara Mahmoud is a Data Scientist with 4 years of experience in predictive modeling, machine learning, and business analytics. Skilled in Python, Pandas, and Scikit-learn with proven ability to extract insights from complex datasets. Worked on projects ranging from customer segmentation to fraud detection.",
    "Youssef Adel is a Mobile Application Developer with 3 years of experience in Flutter and Kotlin. Delivered multiple cross-platform apps with smooth performance and user-friendly interfaces. Skilled in Firebase integration, push notifications, and mobile performance optimization.",
    "Nour El-Din is a Cloud Engineer with 5 years of experience in AWS and Azure. Specialized in cloud infrastructure automation, CI/CD pipelines, and Kubernetes deployments. Successfully led migration of legacy systems to cloud-native architectures.",
    "Mona Ahmed is a UI/UX Designer with 3 years of experience designing intuitive digital experiences. Skilled in Figma, Adobe XD, and prototyping tools. Known for creating wireframes, mockups, and user flows that balance aesthetics with functionality.",
    "Ali Hassan has 4 years of experience as a DevOps Engineer. Expert in Docker, Kubernetes, Jenkins, and GitHub Actions. Proven track record in automating infrastructure, ensuring CI/CD reliability, and monitoring production environments for high availability.",
    "Fatma Gamal is a Business Analyst with 5 years of experience in requirement gathering, process improvement, and stakeholder management. Adept at bridging communication between business and technical teams to deliver data-driven solutions.",
    "Karim Yasser is a Cybersecurity Specialist with 4 years of hands-on experience in penetration testing, threat detection, and incident response. Skilled in SIEM tools, network security, and risk assessment to safeguard enterprise systems.",
    "Salma Fathy is a Machine Learning Engineer with 3 years of experience in developing and deploying ML models. Skilled in TensorFlow, PyTorch, and model optimization. Worked on recommender systems, computer vision, and NLP applications.",
    "Ahmed Magdy has 6 years of experience as a Database Administrator. Skilled in MySQL, PostgreSQL, and MongoDB. Expert at designing schemas, optimizing queries, ensuring high availability, and implementing backup/recovery strategies.",
    "Laila Hassan is a Project Manager with 7 years of experience in Agile and Scrum methodologies. Skilled in project planning, resource allocation, and team leadership. Successfully managed multi-million-dollar software delivery projects on time and within budget.",
    "Omar Sherif is an Embedded Systems Engineer with 4 years of experience in C/C++, ARM microcontrollers, and IoT solutions. Skilled in firmware development, sensor integration, and real-time systems for automotive and industrial applications.",
    "Dina Mostafa is a QA Engineer with 3 years of experience in manual and automated testing. Proficient in Selenium, JUnit, and API testing tools. Experienced in creating test plans, bug tracking, and ensuring product quality across web and mobile applications."
]
